// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntryFromAccountId(ctx context.Context, arg ListEntryFromAccountIdParams) ([]Entry, error)
	ListTransfersFromAccountId(ctx context.Context, arg ListTransfersFromAccountIdParams) ([]ListTransfersFromAccountIdRow, error)
	ListTransfersToAccountId(ctx context.Context, arg ListTransfersToAccountIdParams) ([]Transfer, error)
	SeachEntriesByAccountOwner(ctx context.Context, arg SeachEntriesByAccountOwnerParams) ([]Entry, error)
	SeachTransfersByAccountOwner(ctx context.Context, arg SeachTransfersByAccountOwnerParams) ([]SeachTransfersByAccountOwnerRow, error)
	SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
